disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
included:
  - TennerGrid
excluded:
  - Carthage
  - Pods
  - build
  - DerivedData
line_length: 120
type_body_length: 300
file_length: 500
